name: CI Lite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quick-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies with pip (faster)
      timeout-minutes: 5
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy matplotlib pytest flake8
        pip install -e .
    
    - name: Lint with flake8 (critical errors only)
      timeout-minutes: 2
      run: |
        flake8 audio_lib/ --count --select=E9,F63,F7,F82 --show-source --statistics --max-line-length=127
    
    - name: Quick test
      timeout-minutes: 5
      run: |
        python -m pytest tests/test_oscillators.py -v
        python run_tests.py quick
